/**
 * This function is temporary placeholder for proper error tracking
 */
export const captureException = (...args: any[]): void => {
  console.error(...args);
};
